[project]
name = "_my-pytools"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beartype>=0.22.9",
    "mypy>=2.1.0",
]

[project.scripts]
_my-maintain = "_my_pytools.cli:main_maintenance"
_my-setup = "_my_pytools.cli:setup_project"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"